### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by yabar** [yabar/SEBC#1]

**Comment by yabar** [comment]
**nscd service** and **ntpd service** are not running; not sure if this is important ?

**Comment by yabar** [comment]
Fail to start **Cloudera manager** service

Resolution :
Execute` ./scm_prepare_database.sh -u root -p mysql scm scm -f`

**Comment by yabar** [comment]
MySQL slave can't connect to master

Resolution :
Open port for MySQL in AWS's security rules

**Comment by yabar** [comment]
Unable to start Datanodes
error "Failed to start role"

Resolution :
Data already existed in datanode.dir (/dfs/dn/)
and folder was locked from "in_use.lock"
-> clear data in /dfs/dn
rm -rf /dfs/dn/current

**Comment by yabar** [comment]
Can't install Oozie
error "Failed to execute command Install Oozie ShareLib on service Oozie"

Resolution :
Not actually Oozie problem
need to solve hdfs - unable to put files

**Comment by yabar** [comment]
HDFS isn't properly working e.g. can't put file / fail on canary test

Resolution :
Change Datanode's role group to default
restart cloudera scm agent
service cloudera-scm-agent restart

**Comment by mfernest** [comment]
I wonder how changing the role group had anything to do with the ability to add files. That is a non-intuitive resolution.

**Comment by yabar** [comment]
When I tried to put file to HDFS, it showed error "There are 4 datanode(s) running and 4 node(s) are excluded in this operation"
So, I searched why all nodes are excluded. Some of them indicated something about the role group and in my config, the Datanodes are in the different role group.

It seems doesn't relevant to me as well. May be I can just restart the service to make this work.
